FROM node:24-alpine3.22

WORKDIR /build/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci --no-audit --no-fund
COPY frontend/ ./
RUN npm run lint \
    && npm run typecheck \
    && npm run build \
    && npm run test -- --run
